### ISSUE TITLE
[Bug] - Fails to download gallery

### ISSUE THREAD

**Issue by jeantoulza** [Cirx08/WeddingShare#101]
**Description:**
From the tab `/Admin#galleries` I can see my gallery with some photos in it. The button to download gallery is clickable but clicking it opens a popup with error "Failed to download gallery".

**Expected Behaviour:**
The gallery should download as expected.

**Reproduction Steps:**
Steps to reproduce the behaviour:
1. Go to Admin panel
2. Click the Gallery tab
3. Click the Download button next to the "open" link

F12 shows a POST to `/Gallery/DownloadGallery` with payload `Id=1&SecretKey=`
Response: `{"success":false,"message":"Failed to download gallery"}`

I should add that I'm using the "single" gallery mode with no secret key.

**Cache Cleared:**
Cache cleared, issue persists

**Docker Compose:**
```yaml
services:
  wedding-share:
    container_name: WeddingShare
    image: cirx08/wedding_share:latest
    # ports:
    #  - '${HTTP_PORT:-8080}:5000/tcp'
    environment:
      TITLE: 'WeddingShare'
      ACCOUNT_ADMIN_USERNAME: 'admin'
      ACCOUNT_ADMIN_PASSWORD: 'admin'
      DATABASE_TYPE: 'sqlite'
      ENCRYPTION_KEY: 'ChangeMe'
      ENCRYPTION_SALT: 'ChangeMe'
    volumes:
      - data-volume-config:/app/config
      - data-volume-thumbnails:/app/wwwroot/thumbnails
      - data-volume-uploads:/app/wwwroot/uploads
      - data-volume-custom-resources:/app/wwwroot/custom_resources
    hostname: wedding-share
    restart: always
    networks:
      - web

networks:
  web:
    external: true

volumes:
  data-volume-config:
    name: WeddingShare-Config
  data-volume-thumbnails:
    name: WeddingShare-Thumbnails
  data-volume-uploads:
    name: WeddingShare-Uploads
  data-volume-custom-resources:
    name: WeddingShare-CustomResources
```

**Device:**
Happens on all my devices (laptop w/ Linux, Android phone).

**Screenshots:**
Will provide if needed.

**Additional Details:**
Nothing in my Docker logs.
