### ISSUE TITLE
[Bug] - Translations doesn't automatically

### ISSUE THREAD

**Issue by Sosotess93** [Cirx08/WeddingShare#103]
Description:
The default language is set to French ("fr-FR") through environment variables and/or appsettings.json, but the application always starts in English. When users manually switch the language to French, it works correctly, but it doesn't use French as the default language on initial load.
Expected Behaviour:
The application should automatically load in French on first visit without requiring users to manually switch the language. Also, there should be no option to switch to other languages as I want to enforce French as the only available language.
Reproduction Steps:

Deploy the Docker image with LANGUAGES_DEFAULT="fr-FR" set in environment variables
Open the application in a new browser session
Observe that the interface is still in English, not French
Click on the language selector and switch to French manually
Observe that only then does the interface change to French

Cache Cleared:
Yes, I've cleared browser cache and cookies, and tested in incognito/private browsing mode. The issue persists.
Docker Compose:

```
yamlversion: "3"

services:
  wedding-share:
    container_name: WeddingShare
    image: cirx08/wedding_share:latest
    ports:
      - "5050:5000/tcp"
    environment:
      TITLE: "Sofiane & Soumia"
      ACCOUNT_ADMIN_USERNAME: "admin"
      ACCOUNT_ADMIN_PASSWORD: "admin"
      DATABASE_TYPE: "sqlite"
      ENCRYPTION_KEY: "ChangeMe"
      ENCRYPTION_SALT: "ChangeMe"
      LANGUAGES_DEFAULT: "fr-FR"
      SINGLE_GALLERY_MODE: "true"
      SINGLE_GALLERY_NAME: "Notre Mariage"
      GALLERY_COLUMNS: "4"
      GALLERY_ALLOWED_FILE_TYPES: ".jpg,.jpeg,.png,.mp4,.mov"
      GALLERY_MAX_FILE_SIZE_MB: "10"
      GALLERY_REQUIRE_REVIEW: "false"
    volumes:
      - data-volume-config:/app/config
      - data-volume-thumbnails:/app/wwwroot/thumbnails
      - data-volume-uploads:/app/wwwroot/uploads
      - data-volume-custom-resources:/app/wwwroot/custom_resources

```

The issue is consistent across all tested devices and browsers.

Screenshots:
[No screenshots attached, but you can reproduce the issue by visiting https://weddingshare-amd64-latest.onrender.com/ - login with admin/admin]

Additional Details:
I've also tried adding a custom appsettings.json file with "Default": "fr-FR" in the Languages section, but the issue persists. I want to enforce French as the only language option for all users with no ability to switch to other languages.
