### ISSUE TITLE
[Bug] - Login "Invalid username or password specified" error after upgrade to 1.6.7, even with hardcoded user/password in docker compose file

### ISSUE THREAD

**Issue by maltokyo** [Cirx08/WeddingShare#109]
**Description:**
My user and password has been specified for more than a month in the docker compose file and was working without issue.  After upgrading (I think to 1.6.7), the login just doesnt work anymore..)

i.e. when I log in with `MYUSER` and `MYPASS` from the below docker compose file, it does not let me login.  How can I reset the password, or fix this?

**Expected Behaviour:**
Can login

**Reproduction Steps:**
Steps to reproduce the behaviour:
1. Try to login
2. get error "Invalid username or password specified"

**Cache Cleared:**
If the issue is a front end issue please confirm you have first attempted to clear the cache and the issue still persists.

Confirmed

**Docker Compose:**
If possible please provide your compose setup or a list of environment variables to help debug the issue.

```
services:
  wedding-share:
    container_name: wedding-share
    image: cirx08/wedding_share:latest
     ports:
       - '${HTTP_PORT:-8080}:5000/tcp'
    environment:
      TITLE: 'Wedding Pics/Vids Sharing'
      ACCOUNT_ADMIN_USERNAME: 'MYUSER'
      ACCOUNT_ADMIN_PASSWORD: 'MYPASS'
      DATABASE_TYPE: 'sqlite'
      ENCRYPTION_KEY: 'REDACTED'
      ENCRYPTION_SALT: 'REDACTED'
    volumes:
      - ./z_config:/app/config
      - ./z_thumbnails:/app/wwwroot/thumbnails
      - ./z_uploads:/app/wwwroot/uploads
      - ./z_custom_resources:/app/wwwroot/custom_resources
    restart: unless-stopped


networks:
  default:
    external: true
    name: wedding-share

```

**Device:**
Pleases tell me some more details about the device you are having the issue on. Is the issue isolated to the device or can you reproduce on multiple devices?

 - All devices, mobile, mac and pc
