### ISSUE TITLE
[Bug] - Non default admin username fails if at least one uppcase is included

### ISSUE THREAD

**Issue by Pr0mises** [Cirx08/WeddingShare#85]
**Description:**
Using ACCOUNT_ADMIN_USERNAME and/or ACCOUNT_ADMIN_PASSWORD fails the admin login.
I've no weird characters in it like `$` `&` etc.

Without using them: `admin:admin` works but if one of those variables are set nothing works anymore, not even `admin:admin`

**Expected Behaviour:**
Being able to change the admin username and password and login with it

**Reproduction Steps:**
Steps to reproduce the behaviour:
1. Set ACCOUNT_ADMIN_PASSWORD and/or ACCOUNT_ADMIN_USERNAME in the Docker-Compose
2. Go to the Admin login page
3. Login with the provided credentials
4. `Invalid username or password specified`
5. 
**Cache Cleared:**
Yes

**Docker Compose:**
```yaml
services:
  wedding-share:
    container_name: WeddingShare
    image: cirx08/wedding_share:latest
    ports:
      - ${HTTP_PORT:-8080}:5000/tcp
    environment:
      TITLE: Test
      GALLERY_COLUMNS: 4
      GALLERY_ALLOWED_FILE_TYPES: .jpg,.jpeg,.png,.mp4,.mov
      GALLERY_MAX_FILE_SIZE_MB: 100000
      GALLERY_SECRET_KEY: ${GALLERY_SECRET_KEY}
      DATABASE_TYPE: sqlite
      ACCOUNT_ADMIN_USERNAME: ${ACCOUNT_ADMIN_USERNAME}
      ACCOUNT_ADMIN_PASSWORD: ${ACCOUNT_ADMIN_PASSWORD}
      ACCOUNT_LOCKOUT_ATTEMPTS: 50
      ACCOUNT_LOCKOUT_MINS: 0
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      ENCRYPTION_SALT: ${ENCRYPTION_SALT}
    volumes:
      - /root/docker/wedding/config:/app/config
      - /root/docker/wedding/thumbnails:/app/wwwroot/thumbnails
      - /root/docker/wedding/uploads:/app/wwwroot/uploads
    network_mode: bridge
    hostname: wedding-share
    restart: always
networks: {}
``` 

**Device:**
Pleases tell me some more details about the device you are having the issue on. Is the issue isolated to the device or can you reproduce on multiple devices?

 - Desktop: Windows11 Firefox 136.0

**Additional Details:**
Version: v1.5.7.1
Logs:
```
WeddingShare  | warn: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]
WeddingShare  |       Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed. For more information go to https://aka.ms/aspnet/dataprotectionwarning
WeddingShare  | info: WeddingShare.Helpers.Database.SQLiteDatabaseHelper[0]
WeddingShare  |       Using SQLite connection string: 'Data Source=./config/wedding-share.db'
WeddingShare  | 2025-03-06 15:13:30 +00:00 [INF] Beginning database upgrade
WeddingShare  | 2025-03-06 15:13:30 +00:00 [INF] Checking whether journal table exists
WeddingShare  | 2025-03-06 15:13:30 +00:00 [INF] Fetching list of already executed scripts.
WeddingShare  | 2025-03-06 15:13:30 +00:00 [INF] No new scripts need to be executed - completing.
WeddingShare  | warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
WeddingShare  |       No XML encryptor configured. Key {7e17609f-ab06-4b42-9ba6-dc13c66fb8fe} may be persisted to storage in unencrypted form.
WeddingShare  | Hosting environment: Production
WeddingShare  | Content root path: /app
WeddingShare  | Now listening on: http://[::]:5000
WeddingShare  | Application started. Press Ctrl+C to shut down.
WeddingShare  | info: WeddingShare.Helpers.Dbup.DbupMigrator[0]
WeddingShare  |       Password: lnxTBkTMxslVVgVKtu8NyA==
WeddingShare  | warn: Microsoft.AspNetCore.Session.SessionMiddleware[7]
WeddingShare  |       Error unprotecting the session cookie.
WeddingShare  |       System.Security.Cryptography.CryptographicException: The key {3d95c3bf-0724-4609-b08e-42e35eae3d35} was not found in the key ring. For more information go to https://aka.ms/aspnet/dataprotectionwarning
WeddingShare  |          at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
WeddingShare  |          at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
WeddingShare  |          at Microsoft.AspNetCore.Session.CookieProtection.Unprotect(IDataProtector protector, String protectedText, ILogger logger)
WeddingShare  | fail: Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery[7]
WeddingShare  |       An exception was thrown while deserializing the token.
WeddingShare  |       Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The antiforgery token could not be decrypted.
WeddingShare  |        ---> System.Security.Cryptography.CryptographicException: The key {3d95c3bf-0724-4609-b08e-42e35eae3d35} was not found in the key ring. For more information go to https://aka.ms/aspnet/dataprotectionwarning
WeddingShare  |          at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
WeddingShare  |          at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
WeddingShare  |          at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
WeddingShare  |          --- End of inner exception stack trace ---
WeddingShare  |          at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
WeddingShare  |          at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery.GetCookieTokenDoesNotThrow(HttpContext httpContext)
```

## Question:
What is the displayed password inside the logs for? e.g. `lnxTBkTMxslVVgVKtu8NyA==` like in this log?
