### ISSUE TITLE
[Bug] - Insecure QR Codes - "yes" not working

### ISSUE THREAD

**Issue by maltokyo** [Cirx08/WeddingShare#97]
**Description:**
Set Insecure QR Codes to "yes", but still the QR code does not include the secret key (On single and multple gallery modes), even when it is correctly set.

**Expected Behaviour:**
Secret key included in QR Code URL

**Reproduction Steps:**
Steps to reproduce the behaviour:
As above

**Cache Cleared:**
Yes

**Docker Compose:**
```
services:
  wedding-share:
    container_name: wedding-share
    image: cirx08/wedding_share:latest
#     ports:
#       - '${HTTP_PORT:-8080}:5000/tcp'
    environment:
      TITLE: 'redacted'
      ACCOUNT_ADMIN_USERNAME: 'redacted'
      ACCOUNT_ADMIN_PASSWORD: 'redacted'
      DATABASE_TYPE: 'sqlite'
      ENCRYPTION_KEY: 'redacted'
      ENCRYPTION_SALT: 'redacted'
    volumes:
      - ./z_config:/app/config
      - ./z_thumbnails:/app/wwwroot/thumbnails
      - ./z_uploads:/app/wwwroot/uploads
      - ./z_custom_resources:/app/wwwroot/custom_resources
    restart: unless-stopped
```

**Device:**
Standard web interface, when scanning QR Code, secret key is not included

**Screenshots:**

**Additional Details:**
